version: '3.8'

services:
  # ApexOrchestrator Main Application
  apex-orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apex-orchestrator
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - MODEL_PROVIDER=ollama
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WORK_DIR=/workspace
    volumes:
      - ./logs:/app/logs
      - apex-workspace:/workspace
    restart: unless-stopped
    depends_on:
      - ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - apex-network

  # Ollama Service (if running in Docker)
  ollama:
    image: ollama/ollama:latest
    container_name: apex-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - apex-network
    # Uncomment if you have NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  apex-workspace:
    driver: local
  ollama-models:
    driver: local

networks:
  apex-network:
    driver: bridge
