shell_allow:
  - "git clone "
  - "git pull"
  - "python "
  - "pip install "
  - "docker compose "
  - "docker run "
  - "dir"
  - "type "
  - "copy "
  - "move "
  - "mkdir "
  - "rmdir "
  - "powershell -File "

paths_allow:
  - "C:\\ApexWork"
  - "C:\\ApexOrchestrator"
  - "/app/work"  # Docker container work directory

timeouts:
  shell_seconds: 120
  python_seconds: 120
  http_seconds: 30

network:
  http_allow_domains:
    - "api.github.com"
    - "raw.githubusercontent.com"
    - "pypi.org"
    - "files.pythonhosted.org"
